// src/components/ui/Tab.tsx
import type { FC, TeactNode } from '../../lib/teact/teact';
import React, { useEffect, useLayoutEffect, useRef } from '../../lib/teact/teact';

import type { MenuItemContextAction } from './ListItem';

import { requestForcedReflow, requestMutation } from '../../lib/fasterdom/fasterdom';
import buildClassName from '../../util/buildClassName';
import forceReflow from '../../util/forceReflow';
import { MouseButton } from '../../util/windowEnvironment';
import renderText from '../common/helpers/renderText';

import useContextMenuHandlers from '../../hooks/useContextMenuHandlers';
import { useFastClick } from '../../hooks/useFastClick';
import useLastCallback from '../../hooks/useLastCallback';

import Icon from '../common/icons/Icon';
import Menu from './Menu';
import MenuItem from './MenuItem';
import MenuSeparator from './MenuSeparator';

import './Tab.scss';

type OwnProps = {
  className?: string;
  title: TeactNode;
  isActive?: boolean;
  isBlocked?: boolean;
  badgeCount?: number;
  isBadgeActive?: boolean;
  previousActiveTab?: number;
  onClick?: (arg: number) => void;
  clickArg?: number;
  contextActions?: MenuItemContextAction[];
  contextRootElementSelector?: string;
};

const classNames = {
  active: 'Tab--active',
  badgeActive: 'Tab__badge--active',
};

const Tab: FC<OwnProps> = ({
  className,
  title,
  isActive,
  isBlocked,
  badgeCount,
  isBadgeActive,
  previousActiveTab,
  onClick,
  clickArg,
  contextActions,
  contextRootElementSelector,
}) => {
  // eslint-disable-next-line no-null/no-null
  const tabRef = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    // Set initial active state
    if (isActive && previousActiveTab === undefined && tabRef.current) {
      tabRef.current!.classList.add(classNames.active);
    }
  }, [isActive, previousActiveTab]);

  useEffect(() => {
    if (!isActive || previousActiveTab === undefined) {
      return;
    }

    const tabEl = tabRef.current!;
    const prevTabEl = tabEl.parentElement!.children[previousActiveTab];
    if (!prevTabEl) {
      // The number of tabs in the parent component has decreased. It is necessary to add the active tab class name.
      if (isActive && !tabEl.classList.contains(classNames.active)) {
        requestMutation(() => {
          tabEl.classList.add(classNames.active);
        });
      }
      return;
    }

    const platformEl = tabEl.querySelector<HTMLElement>('.platform')!;
    const prevPlatformEl = prevTabEl.querySelector<HTMLElement>('.platform')!;

    // We move and resize the platform, so it repeats the position and size of the previous one
    const shiftLeft = prevPlatformEl.parentElement!.offsetLeft - platformEl.parentElement!.offsetLeft;
    const scaleFactor = prevPlatformEl.clientWidth / platformEl.clientWidth;

    requestMutation(() => {
      prevPlatformEl.classList.remove('animate');
      platformEl.classList.remove('animate');
      platformEl.style.transform = `translate3d(${shiftLeft}px, 0, 0) scale3d(${scaleFactor}, 1, 1)`;

      requestForcedReflow(() => {
        forceReflow(platformEl);

        return () => {
          platformEl.classList.add('animate');
          platformEl.style.transform = 'none';

          prevTabEl.classList.remove(classNames.active);
          tabEl.classList.add(classNames.active);
        };
      });
    });
  }, [isActive, previousActiveTab]);

  const {
    contextMenuAnchor, handleContextMenu, handleBeforeContextMenu, handleContextMenuClose,
    handleContextMenuHide, isContextMenuOpen,
  } = useContextMenuHandlers(tabRef, !contextActions);

  const { handleClick, handleMouseDown } = useFastClick((e: React.MouseEvent<HTMLDivElement>) => {
    if (contextActions && (e.button === MouseButton.Secondary || !onClick)) {
      handleBeforeContextMenu(e);
    }

    if (e.type === 'mousedown' && e.button !== MouseButton.Main) {
      return;
    }

    onClick?.(clickArg!);
  });

  const getTriggerElement = useLastCallback(() => tabRef.current);
  const getRootElement = useLastCallback(
    () => (contextRootElementSelector ? tabRef.current!.closest(contextRootElementSelector) : document.body),
  );
  const getMenuElement = useLastCallback(
    () => document.querySelector('#portals')!.querySelector('.Tab-context-menu .bubble'),
  );
  const getLayout = useLastCallback(() => ({ withPortal: true }));

  return (
    <div
      className={buildClassName('Tab', onClick && 'Tab--interactive', className)}
      onClick={handleClick}
      onMouseDown={handleMouseDown}
      onContextMenu={handleContextMenu}
      ref={tabRef}
    >
      <span className="Tab_inner">
        {typeof title === 'string' ? renderText(title) : title}
        {Boolean(badgeCount) && (
          <span className={buildClassName('badge', isBadgeActive && classNames.badgeActive)}>{badgeCount}</span>
        )}
        {isBlocked && <Icon name="lock-badge" className="blocked" />}
        <i className="platform" />
      </span>

      {contextActions && contextMenuAnchor !== undefined && (
        <Menu
          isOpen={isContextMenuOpen}
          anchor={contextMenuAnchor}
          getTriggerElement={getTriggerElement}
          getRootElement={getRootElement}
          getMenuElement={getMenuElement}
          getLayout={getLayout}
          className="Tab-context-menu"
          autoClose
          onClose={handleContextMenuClose}
          onCloseAnimationEnd={handleContextMenuHide}
          withPortal
        >
          {contextActions.map((action) => (
            ('isSeparator' in action) ? (
              <MenuSeparator key={action.key || 'separator'} />
            ) : (
              <MenuItem
                key={action.title}
                icon={action.icon}
                destructive={action.destructive}
                disabled={!action.handler}
                onClick={action.handler}
              >
                {action.title}
              </MenuItem>
            )
          ))}
        </Menu>
      )}
    </div>
  );
};

export default Tab;

// src/components/ui/svelte/Tab.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { TeactNode } from '../../../lib/teact/teact';
  import type { MenuItemContextAction } from './ListItem.svelte';

  import { requestForcedReflow, requestMutation } from '../../../lib/fasterdom/fasterdom';
  import { MouseButton } from '../../../util/browser/windowEnvironment';
  import buildClassName from '../../../util/buildClassName';
  import forceReflow from '../../../util/forceReflow';
  import renderText from '../../common/helpers/renderText';

  import Icon from '../../common/icons/svelte/Icon.svelte';
  import Menu from './Menu.svelte';
  import MenuItem from './MenuItem.svelte';
  import MenuSeparator from './MenuSeparator.svelte';

  interface Props {
    className?: string;
    title: TeactNode;
    isActive?: boolean;
    isBlocked?: boolean;
    badgeCount?: number;
    isBadgeActive?: boolean;
    previousActiveTab?: number;
    onclick?: (arg: number) => void;
    clickArg?: number;
    contextActions?: MenuItemContextAction[];
    contextRootElementSelector?: string;
    icon?: TeactNode;
  }

  let {
    className,
    title,
    isActive,
    isBlocked,
    badgeCount,
    isBadgeActive,
    previousActiveTab,
    contextActions,
    contextRootElementSelector,
    icon,
    clickArg,
    onclick,
  }: Props = $props();

  let tabRef: HTMLButtonElement | undefined;
  let isContextMenuOpen = $state(false);
  let contextMenuAnchor = $state<{ x: number; y: number } | undefined>(undefined);

  const classNames = {
    active: 'Tab--active',
    badgeActive: 'Tab__badge--active',
  };

  // Mimic useLayoutEffect for initial active state
  onMount(() => {
    if (isActive && previousActiveTab === undefined && tabRef) {
      tabRef.classList.add(classNames.active);
    }
  });

  // Mimic useEffect for tab transitions using $effect
  $effect(() => {
    if (!isActive || previousActiveTab === undefined || !tabRef) {
      return;
    }

    const tabEl = tabRef;
    const parent = tabEl.parentElement;
    if (!parent) return;

    const prevTabEl = parent.children[previousActiveTab] as HTMLElement | null;
    if (!prevTabEl) {
      if (isActive && !tabEl.classList.contains(classNames.active)) {
        requestMutation(() => {
          tabEl.classList.add(classNames.active);
        });
      }
      return;
    }

    const platformEl = tabEl.querySelector<HTMLElement>('.platform')!;
    const prevPlatformEl = prevTabEl.querySelector<HTMLElement>('.platform')!;

    const shiftLeft = prevPlatformEl.parentElement!.offsetLeft - platformEl.parentElement!.offsetLeft;
    const scaleFactor = prevPlatformEl.clientWidth / platformEl.clientWidth;

    requestMutation(() => {
      prevPlatformEl.classList.remove('animate');
      platformEl.classList.remove('animate');
      platformEl.style.transform = `translate3d(${shiftLeft}px, 0, 0) scale3d(${scaleFactor}, 1, 1)`;

      requestForcedReflow(() => {
        forceReflow(platformEl);

        return () => {
          platformEl.classList.add('animate');
          platformEl.style.transform = 'none';

          prevTabEl.classList.remove(classNames.active);
          tabEl.classList.add(classNames.active);
        };
      });
    });
  });

  function handleClick(e: MouseEvent) {
    if (contextActions && (e.button === MouseButton.Secondary || !onclick)) {
      handleBeforeContextMenu(e);
    }

    if (e.type === 'mousedown' && e.button !== MouseButton.Main) {
      return;
    }

    onclick?.(clickArg!);
  }

  function handleMouseDown(e: MouseEvent) {
    // Mimic useFastClick's mousedown logic
    if (e.button !== MouseButton.Main) {
      return;
    }
  }

  function handleContextMenu(e: MouseEvent) {
    if (!contextActions) return;
    e.preventDefault();
    e.stopPropagation();
    contextMenuAnchor = { x: e.clientX, y: e.clientY };
    isContextMenuOpen = true;
  }

  function handleBeforeContextMenu(e: MouseEvent) {
    if (!contextActions) return;
    e.preventDefault();
    e.stopPropagation();
    contextMenuAnchor = { x: e.clientX, y: e.clientY };
    isContextMenuOpen = true;
  }

  function handleContextMenuClose() {
    isContextMenuOpen = false;
  }

  function handleContextMenuHide() {
    contextMenuAnchor = undefined;
  }

  const getTriggerElement = () => tabRef as HTMLElement | undefined;
  const getRootElement: () => HTMLElement | undefined = () => {
    if (contextRootElementSelector) {
      const el = tabRef!.closest(contextRootElementSelector);
      return el instanceof HTMLElement ? el : undefined;
    }
    return document.body;
  };
  const getMenuElement = () => document.querySelector('#portals')!.querySelector('.Tab-context-menu .bubble');
  const getLayout = () => ({ withPortal: true });

</script>

<button
  type="button"
  class={buildClassName('Tab', onclick && 'Tab--interactive', className)}
  onclick={handleClick}
  onmousedown={handleMouseDown}
  oncontextmenu={handleContextMenu}
  bind:this={tabRef}
>
  {#if icon}
    {icon}
  {/if}
  <span class="Tab_inner">
    {#if typeof title === 'string'}
      {@html renderText(title)}
    {:else}
      {title}
    {/if}
    {#if badgeCount}
      <span class={buildClassName('badge', isBadgeActive && classNames.badgeActive)}>{badgeCount}</span>
    {/if}
    {#if isBlocked}
      <Icon name="lock-badge" className="blocked" />
    {/if}
    <i class="platform"></i>
  </span>

  {#if contextActions && contextMenuAnchor !== undefined && isContextMenuOpen}
    <Menu
      isOpen={isContextMenuOpen}
      anchor={contextMenuAnchor}
      getTriggerElement={getTriggerElement}
      getRootElement={getRootElement}
      getMenuElement={getMenuElement}
      getLayout={getLayout}
      className="Tab-context-menu"
      autoClose
      onclose={handleContextMenuClose}
      onCloseAnimationEnd={handleContextMenuHide}
      withPortal
    >
      {#each contextActions as action}
        {#if 'isSeparator' in action}
          <MenuSeparator />
        {:else}
          <MenuItem
            icon={action.icon}
            destructive={action.destructive}
            disabled={!action.handler}
            onclick={action.handler}
          >
            {action.title}
          </MenuItem>
        {/if}
      {/each}
    </Menu>
  {/if}
</button>

<style lang="scss">
  @import "../Tab.scss";
</style>
