// src/components/auth/svelte/Auth.svelte
<script lang="ts">
  import { globalStore } from '../../../global/store.svelte';
  import { IS_TAURI } from '../../../util/browser/globalEnvironment';
  import { IS_MAC_OS, PLATFORM_ENV } from '../../../util/browser/windowEnvironment';
  
  import AuthPhoneNumber from './AuthPhoneNumber.svelte';
  import AuthCode from './AuthCode.svelte';
  import AuthPassword from './AuthPassword.svelte';
  // import AuthQrCode from './AuthQrCode.svelte';
  // import AuthRegister from './AuthRegister.svelte';

  const authState = $derived(globalStore.state.auth.state);
  const isMobile = PLATFORM_ENV === 'iOS' || PLATFORM_ENV === 'Android';

  // Simplified version of the transition logic for now
  const activeComponent = $derived.by(() => {
    switch (authState) {
      case 'authorizationStateWaitCode': return AuthCode;
      case 'authorizationStateWaitPassword': return AuthPassword;
      // case 'authorizationStateWaitRegistration': return AuthRegister;
      case 'authorizationStateWaitPhoneNumber': return AuthPhoneNumber;
      // case 'authorizationStateWaitQrCode': return AuthQrCode;
      default: return isMobile ? AuthPhoneNumber : AuthPhoneNumber; // Placeholder for QrCode
    }
  });
</script>

<div class="Auth fade" data-tauri-drag-region={IS_TAURI && IS_MAC_OS ? true : undefined}>
  <!-- Transition component placeholder -->
  <activeComponent></activeComponent>
</div>

<style lang="scss">
  @import "../Auth.scss";
  
  .fade {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
  }
</style>

// src/components/auth/Auth.tsx
import '../../global/actions/initial';

import { memo } from '../../lib/teact/teact';
import { getActions, withGlobal } from '../../global';

import type { GlobalState } from '../../global/types';

import { IS_TAURI } from '../../util/browser/globalEnvironment';
import { IS_MAC_OS, PLATFORM_ENV } from '../../util/browser/windowEnvironment';

import useCurrentOrPrev from '../../hooks/useCurrentOrPrev';
import useHistoryBack from '../../hooks/useHistoryBack';

import Transition from '../ui/Transition';
import AuthCode from './AuthCode.async';
import AuthPassword from './AuthPassword.async';
import AuthPhoneNumber from './AuthPhoneNumber';
import AuthQrCode from './AuthQrCode';
import AuthRegister from './AuthRegister.async';

import './Auth.scss';

type StateProps = {
  authState: GlobalState['auth']['state'];
};

const Auth = ({
  authState,
}: StateProps) => {
  const {
    returnToAuthPhoneNumber, goToAuthQrCode,
  } = getActions();

  const isMobile = PLATFORM_ENV === 'iOS' || PLATFORM_ENV === 'Android';

  const handleChangeAuthorizationMethod = () => {
    if (!isMobile) {
      goToAuthQrCode();
    } else {
      returnToAuthPhoneNumber();
    }
  };

  useHistoryBack({
    isActive: (!isMobile && authState === 'authorizationStateWaitPhoneNumber')
      || (isMobile && authState === 'authorizationStateWaitQrCode'),
    onBack: handleChangeAuthorizationMethod,
  });

  // For animation purposes
  const renderingAuthState = useCurrentOrPrev(
    authState !== 'authorizationStateReady' ? authState : undefined,
    true,
  );

  function getScreen() {
    switch (renderingAuthState) {
      case 'authorizationStateWaitCode':
        return <AuthCode />;
      case 'authorizationStateWaitPassword':
        return <AuthPassword />;
      case 'authorizationStateWaitRegistration':
        return <AuthRegister />;
      case 'authorizationStateWaitPhoneNumber':
        return <AuthPhoneNumber />;
      case 'authorizationStateWaitQrCode':
        return <AuthQrCode />;
      default:
        return isMobile ? <AuthPhoneNumber /> : <AuthQrCode />;
    }
  }

  function getActiveKey() {
    switch (renderingAuthState) {
      case 'authorizationStateWaitCode':
        return 0;
      case 'authorizationStateWaitPassword':
        return 1;
      case 'authorizationStateWaitRegistration':
        return 2;
      case 'authorizationStateWaitPhoneNumber':
        return 3;
      case 'authorizationStateWaitQrCode':
        return 4;
      default:
        return isMobile ? 3 : 4;
    }
  }

  return (
    <Transition
      activeKey={getActiveKey()}
      name="fade"
      className="Auth"
      data-tauri-drag-region={IS_TAURI && IS_MAC_OS ? true : undefined}
    >
      {getScreen()}
    </Transition>
  );
};

export default memo(withGlobal(
  (global): Complete<StateProps> => {
    return {
      authState: global.auth.state,
    };
  },
)(Auth));
