// src/components/auth/svelte/AuthCode.svelte
<script lang="ts">
  import { getActions } from '../../../global';
  import { globalStore } from '../../../global/store.svelte';
  import Icon from '../../common/icons/svelte/Icon.svelte';
  import InputText from '../../ui/svelte/InputText.svelte';
  import Loading from '../../ui/svelte/Loading.svelte';

  const CODE_LENGTH = 5;

  let code = $state('');
  let isTracking = $state(false);
  let trackingDirection = $state(1);

  // Derived global state
  const auth = $derived(globalStore.state.auth);
  const phoneNumber = $derived(auth.phoneNumber);
  const isCodeViaApp = $derived(auth.isCodeViaApp);
  const isLoading = $derived(auth.isLoading);
  const errorKey = $derived(auth.errorKey);

  function handleReturnToAuthPhoneNumber() {
    getActions().returnToAuthPhoneNumber();
  }

  function onCodeChange(e: Event) {
    if (errorKey) {
      getActions().clearAuthErrorKey();
    }

    const target = e.target as HTMLInputElement;
    const nextCode = target.value.replace(/[^\d]+/g, '').slice(0, CODE_LENGTH);
    target.value = nextCode;

    if (nextCode === code) return;

    trackingDirection = nextCode.length >= code.length ? 1 : -1;
    code = nextCode;

    if (!isTracking) {
      isTracking = true;
    } else if (!nextCode.length) {
      isTracking = false;
    }

    if (nextCode.length === CODE_LENGTH) {
      getActions().setAuthCode({ code: nextCode });
    }
  }
</script>

<div id="auth-code-form" class="custom-scroll">
  <div class="auth-form">
    <!-- TrackingMonkey component is omitted/mocked for now, needs rlottie -->
    <div class="tracking-monkey-placeholder"></div>
    
    <h1>
      {phoneNumber}
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        class="auth-number-edit div-button"
        onclick={handleReturnToAuthPhoneNumber}
        role="button"
        tabindex="0"
        title="Wrong number"
        aria-label="Wrong number"
      >
        <Icon name="edit" />
      </div>
    </h1>
    
    <p class="note">
      {isCodeViaApp ? 'We have sent a code to the Telegram app.' : 'We have sent a code via SMS.'}
    </p>
    
    <InputText
      id="sign-in-code"
      label="Code"
      oninput={onCodeChange}
      value={code}
      error={errorKey ? String(errorKey) : undefined}
      autoComplete="off"
      inputMode="numeric"
    />
    
    {#if isLoading}
      <Loading />
    {/if}
  </div>
</div>

<style lang="scss">
  /* Inherits styles from Auth.scss already included in parent */
  .tracking-monkey-placeholder {
    height: 120px;
    width: 120px;
    margin: 0 auto;
  }
</style>

// src/components/auth/AuthCode.tsx
import type { FormEvent } from 'react';
import type { FC } from '../../lib/teact/teact';
import React, {
  memo, useCallback, useEffect, useRef, useState,
} from '../../lib/teact/teact';
import { getActions, withGlobal } from '../../global';

import type { GlobalState } from '../../global/types';

import { IS_TOUCH_ENV } from '../../util/browser/windowEnvironment';
import { pick } from '../../util/iteratees';

import useHistoryBack from '../../hooks/useHistoryBack';
import useLang from '../../hooks/useLang';

import Icon from '../common/icons/Icon';
import TrackingMonkey from '../common/TrackingMonkey';
import InputText from '../ui/InputText';
import Loading from '../ui/Loading';

type StateProps = Pick<GlobalState, 'authPhoneNumber' | 'authIsCodeViaApp' | 'authIsLoading' | 'authErrorKey'>;

const CODE_LENGTH = 5;

const AuthCode: FC<StateProps> = ({
  authPhoneNumber,
  authIsCodeViaApp,
  authIsLoading,
  authErrorKey,
}) => {
  const {
    setAuthCode,
    returnToAuthPhoneNumber,
    clearAuthErrorKey,
  } = getActions();

  const lang = useLang();
  const inputRef = useRef<HTMLInputElement>();

  const [code, setCode] = useState<string>('');
  const [isTracking, setIsTracking] = useState(false);
  const [trackingDirection, setTrackingDirection] = useState(1);

  useEffect(() => {
    if (!IS_TOUCH_ENV) {
      inputRef.current!.focus();
    }
  }, []);

  useHistoryBack({
    isActive: true,
    onBack: returnToAuthPhoneNumber,
  });

  const onCodeChange = useCallback((e: FormEvent<HTMLInputElement>) => {
    if (authErrorKey) {
      clearAuthErrorKey();
    }

    const { currentTarget: target } = e;
    target.value = target.value.replace(/[^\d]+/, '').substr(0, CODE_LENGTH);

    if (target.value === code) {
      return;
    }

    setCode(target.value);

    if (!isTracking) {
      setIsTracking(true);
    } else if (!target.value.length) {
      setIsTracking(false);
    }

    if (code && code.length > target.value.length) {
      setTrackingDirection(-1);
    } else {
      setTrackingDirection(1);
    }

    if (target.value.length === CODE_LENGTH) {
      setAuthCode({ code: target.value });
    }
  }, [authErrorKey, code, isTracking, setAuthCode]);

  function handleReturnToAuthPhoneNumber() {
    returnToAuthPhoneNumber();
  }

  return (
    <div id="auth-code-form" className="custom-scroll">
      <div className="auth-form">
        <TrackingMonkey
          code={code}
          codeLength={CODE_LENGTH}
          isTracking={isTracking}
          trackingDirection={trackingDirection}
        />
        <h1>
          {authPhoneNumber}
          <div
            className="auth-number-edit div-button"
            onClick={handleReturnToAuthPhoneNumber}
            role="button"
            tabIndex={0}
            title={lang('WrongNumber')}
            aria-label={lang('WrongNumber')}
          >
            <Icon name="edit" />
          </div>
        </h1>
        <p className="note">
          {lang(authIsCodeViaApp ? 'SentAppCode' : 'LoginJustSentSms', undefined, {
            withNodes: true,
            withMarkdown: true,
          })}
        </p>
        <InputText
          ref={inputRef}
          id="sign-in-code"
          label={lang('Code')}
          onInput={onCodeChange}
          value={code}
          error={authErrorKey && lang.withRegular(authErrorKey)}
          autoComplete="off"
          inputMode="numeric"
        />
        {authIsLoading && <Loading />}
      </div>
    </div>
  );
};

export default memo(withGlobal(
  (global): StateProps => pick(global, ['authPhoneNumber', 'authIsCodeViaApp', 'authIsLoading', 'authErrorKey']),
)(AuthCode));
