// src/components/auth/svelte/CountryCodeInput.svelte
<script lang="ts">
  import { globalStore } from '../../../global/store.svelte';
  import type { ApiCountryCode } from '../../../api/types';
  import buildClassName from '../../../util/buildClassName';
  import { isoToEmoji } from '../../../util/emoji/emoji';
  import { prepareSearchWordsForNeedle } from '../../../util/searchWords';
  import renderText from '../../common/helpers/renderText';

  import DropdownMenu from '../../ui/svelte/DropdownMenu.svelte';
  import MenuItem from '../../ui/svelte/MenuItem.svelte';
  import Spinner from '../../ui/svelte/Spinner.svelte';

  interface Props {
    id: string;
    value?: ApiCountryCode;
    isLoading?: boolean;
    onchange: (value: ApiCountryCode) => void;
  }

  let { id, value, isLoading, onchange }: Props = $props();

  const phoneCodeList = $derived(globalStore.state.countryList.phoneCodes || []);
  let filter = $state<string | undefined>(undefined);
  
  const filteredList = $derived(getFilteredList(phoneCodeList, filter));

  function getFilteredList(countryList: ApiCountryCode[], filterVal = ''): ApiCountryCode[] {
    if (!filterVal.length) return countryList;
    const searchWords = prepareSearchWordsForNeedle(filterVal);
    return countryList.filter((country) => (
      searchWords(country.defaultName) || (country.name && searchWords(country.name))
    ));
  }

  function updateFilter(filterValue?: string) {
    filter = filterValue;
  }

  function handleChange(country: ApiCountryCode) {
    onchange(country);
    setTimeout(() => updateFilter(undefined), 200);
  }

  function handleInput(e: Event) {
    updateFilter((e.target as HTMLInputElement).value);
  }

  function handleInputKeyDown(e: KeyboardEvent) {
    if (e.key !== 'Backspace') return;
    const target = e.currentTarget as HTMLInputElement;
    if (value && filter === undefined) {
      target.value = '';
    }
    updateFilter(target.value);
  }

  const emoji = $derived(value && isoToEmoji(value.iso2));
  const name = $derived(value?.name || value?.defaultName || '');
  const inputValue = $derived(filter ?? [emoji, name].filter(Boolean).join(' '));
</script>

<DropdownMenu className="CountryCodeInput">
  {#snippet trigger({ onTrigger, isOpen }: { onTrigger: () => void; isOpen: boolean })}
    <div class={buildClassName('input-group', value && 'touched')}>
      <input
        class={buildClassName('form-control', isOpen && 'focus')}
        type="text"
        {id}
        value={inputValue}
        autocomplete="off"
        onclick={() => { onTrigger(); }}
        onfocus={() => { onTrigger(); }}
        oninput={(e) => { handleInput(e); onTrigger(); }}
        onkeydown={handleInputKeyDown}
      />
      <label for={id}>Country</label> <!-- Translation needed -->
      {#if isLoading}
        <Spinner color="black" />
      {:else}
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <i onclick={() => onTrigger()} class={buildClassName('css-icon-down', isOpen && 'open')}></i>
      {/if}
    </div>
  {/snippet}

  {#each filteredList as country (country.iso2 + '-' + country.countryCode)}
    <MenuItem
      className={value && country.iso2 === value.iso2 ? 'selected' : ''}
      onclick={() => handleChange(country)}
    >
      <span class="country-flag">{@html renderText(isoToEmoji(country.iso2), ['hq_emoji'])}</span>
      <span class="country-name">{country.name || country.defaultName}</span>
      <span class="country-code">+{country.countryCode}</span>
    </MenuItem>
  {/each}
  
  {#if filteredList.length === 0}
    <MenuItem disabled>
      <span>No results</span> <!-- Translation needed -->
    </MenuItem>
  {/if}
</DropdownMenu>

<style lang="scss">
  @import "../CountryCodeInput.scss";
</style>

// src/components/auth/CountryCodeInput.tsx
import type { FC } from '../../lib/teact/teact';
import React, {
  memo, useCallback, useRef, useState,
} from '../../lib/teact/teact';
import { withGlobal } from '../../global';

import type { ApiCountryCode } from '../../api/types';

import { ANIMATION_END_DELAY } from '../../config';
import buildClassName from '../../util/buildClassName';
import { isoToEmoji } from '../../util/emoji/emoji';
import { prepareSearchWordsForNeedle } from '../../util/searchWords';
import { IS_EMOJI_SUPPORTED } from '../../util/windowEnvironment';
import renderText from '../common/helpers/renderText';

import useLang from '../../hooks/useLang';
import useSyncEffect from '../../hooks/useSyncEffect';

import DropdownMenu from '../ui/DropdownMenu';
import MenuItem from '../ui/MenuItem';
import Spinner from '../ui/Spinner';

import './CountryCodeInput.scss';

type StateProps = {
  phoneCodeList: ApiCountryCode[];
};

type OwnProps = {
  id: string;
  value?: ApiCountryCode;
  isLoading?: boolean;
  onChange: (value: ApiCountryCode) => void;
};

const MENU_HIDING_DURATION = 200 + ANIMATION_END_DELAY;
const SELECT_TIMEOUT = 50;

const CountryCodeInput: FC<OwnProps & StateProps> = ({
  id,
  value,
  isLoading,
  onChange,
  phoneCodeList,
}) => {
  const lang = useLang();
  // eslint-disable-next-line no-null/no-null
  const inputRef = useRef<HTMLInputElement>(null);

  const [filter, setFilter] = useState<string | undefined>();
  const [filteredList, setFilteredList] = useState<ApiCountryCode[]>([]);

  const updateFilter = useCallback((filterValue?: string) => {
    setFilter(filterValue);
    setFilteredList(getFilteredList(phoneCodeList, filterValue));
  }, [phoneCodeList]);

  useSyncEffect(([prevPhoneCodeList]) => {
    if (!prevPhoneCodeList?.length && phoneCodeList.length) {
      setFilteredList(getFilteredList(phoneCodeList, filter));
    }
  }, [phoneCodeList, filter]);

  const handleChange = useCallback((country: ApiCountryCode) => {
    onChange(country);

    setTimeout(() => updateFilter(undefined), MENU_HIDING_DURATION);
  }, [onChange, updateFilter]);

  const handleInput = useCallback((e: React.FormEvent<HTMLInputElement>) => {
    updateFilter(e.currentTarget.value);
  }, [updateFilter]);

  const handleInputKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.keyCode !== 8) {
      return;
    }

    const target = e.currentTarget;
    if (value && filter === undefined) {
      target.value = '';
    }

    updateFilter(target.value);
  }, [filter, updateFilter, value]);

  const CodeInput: FC<{ onTrigger: () => void; isOpen?: boolean }> = useCallback(({ onTrigger, isOpen }) => {
    const handleTrigger = () => {
      if (isOpen) {
        return;
      }

      setTimeout(() => {
        inputRef.current!.select();
      }, SELECT_TIMEOUT);

      onTrigger();

      const formEl = document.getElementById('auth-phone-number-form')!;
      formEl.scrollTo({ top: formEl.scrollHeight, behavior: 'smooth' });
    };

    const handleCodeInput = (e: React.FormEvent<HTMLInputElement>) => {
      handleInput(e);
      handleTrigger();
    };

    const emoji = value && IS_EMOJI_SUPPORTED && renderText(isoToEmoji(value.iso2), ['hq_emoji']);
    const name = value?.name || value?.defaultName || '';
    const inputValue = filter ?? [emoji, name].filter(Boolean).join(' ');

    return (
      <div className={buildClassName('input-group', value && 'touched')}>
        <input
          ref={inputRef}
          className={buildClassName('form-control', isOpen && 'focus')}
          type="text"
          id={id}
          value={inputValue}
          autoComplete="off"
          onClick={handleTrigger}
          onFocus={handleTrigger}
          onInput={handleCodeInput}
          onKeyDown={handleInputKeyDown}
        />
        <label>{lang('LoginSelectCountryTitle')}</label>
        {isLoading ? (
          <Spinner color="black" />
        ) : (
          <i onClick={handleTrigger} className={buildClassName('css-icon-down', isOpen && 'open')} />
        )}
      </div>
    );
  }, [filter, handleInput, handleInputKeyDown, id, isLoading, lang, value]);

  return (
    <DropdownMenu
      className="CountryCodeInput"
      trigger={CodeInput}
    >
      {filteredList
        .map((country: ApiCountryCode) => (
          <MenuItem
            key={`${country.iso2}-${country.countryCode}`}
            className={value && country.iso2 === value.iso2 ? 'selected' : ''}
            // eslint-disable-next-line react/jsx-no-bind
            onClick={() => handleChange(country)}
          >
            <span className="country-flag">{renderText(isoToEmoji(country.iso2), ['hq_emoji'])}</span>
            <span className="country-name">{country.name || country.defaultName}</span>
            <span className="country-code">+{country.countryCode}</span>
          </MenuItem>
        ))}
      {!filteredList.length && (
        <MenuItem
          key="no-results"
          className="no-results"
          disabled
        >
          <span>{lang('CountryNone')}</span>
        </MenuItem>
      )}
    </DropdownMenu>
  );
};

function getFilteredList(countryList: ApiCountryCode[], filter = ''): ApiCountryCode[] {
  if (!filter.length) {
    return countryList;
  }

  const searchWords = prepareSearchWordsForNeedle(filter);

  return countryList.filter((country) => (
    searchWords(country.defaultName) || (country.name && searchWords(country.name))
  ));
}

export default memo(withGlobal<OwnProps>(
  (global): StateProps => {
    const { countryList: { phoneCodes: phoneCodeList } } = global;
    return {
      phoneCodeList,
    };
  },
)(CountryCodeInput));
