// src/components/ui/svelte/MenuItem.svelte
<script lang="ts">
  import type { IconName } from '../../../types/icons';
  import buildClassName from '../../../util/buildClassName';
  import Icon from '../../common/icons/svelte/Icon.svelte';

  interface Props {
    customIcon?: any;
    className?: string;
    children: any;
    href?: string;
    rel?: string;
    target?: string;
    download?: string;
    disabled?: boolean;
    destructive?: boolean;
    ariaLabel?: string;
    withWrap?: boolean;
    withPreventDefaultOnMouseDown?: boolean;
    icon?: IconName | 'A' | 'K';
    isCharIcon?: boolean;
    onclick?: (e: MouseEvent) => void;
  }

  let {
    icon,
    isCharIcon,
    customIcon,
    className,
    children,
    href,
    target,
    download,
    disabled,
    destructive,
    ariaLabel,
    withWrap,
    rel = 'noopener noreferrer',
    withPreventDefaultOnMouseDown,
    onclick
  }: Props = $props();

  function handleClick(e: MouseEvent) {
    if (disabled) {
      e.preventDefault();
      return;
    }
    onclick?.(e);
  }

  function handleMouseDown(e: MouseEvent) {
    if (withPreventDefaultOnMouseDown) {
      e.preventDefault();
    }
  }

  const fullClassName = $derived(buildClassName(
    'MenuItem',
    className,
    disabled && 'disabled',
    destructive && 'destructive',
    withWrap && 'wrap',
    !icon && !customIcon && 'text-only'
  ));
</script>

{#snippet content()}
  {#if !customIcon && icon}
    <Icon name={isCharIcon ? 'char' : icon as IconName} character={isCharIcon ? icon : undefined} />
  {/if}
  {#if customIcon}
    {@render customIcon()}
  {/if}
  {@render children()}
{/snippet}

{#if href && !disabled}
  <a
    tabindex="0"
    class={fullClassName}
    {href}
    {download}
    aria-label={ariaLabel}
    title={ariaLabel}
    {target}
    {rel}
    onclick={handleClick}
    onmousedown={handleMouseDown}
  >
    {@render content()}
  </a>
{:else}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div
    role="menuitem"
    tabindex="0"
    class={fullClassName}
    onclick={handleClick}
    onmousedown={handleMouseDown}
    aria-label={ariaLabel}
    title={ariaLabel}
  >
    {@render content()}
  </div>
{/if}

<style lang="scss">
  @import "../MenuItem.scss";
</style>

// src/components/ui/MenuItem.react.tsx
import React from 'react';
import type { FC } from '../../lib/teact/teact';

import type { IconName } from '../../types/icons';

import { IS_TEST } from '../../config';
import buildClassName from '../../util/buildClassName';

import useAppLayout from '../../hooks/useAppLayout.react';
import useLang from '../../hooks/useLang.react';
import useLastCallback from '../../hooks/useLastCallback.react';

import './MenuItem.scss';

export type MenuItemProps = {
  icon?: IconName | 'A' | 'K';
  isCharIcon?: boolean;
  customIcon?: React.ReactNode;
  className?: string;
  children: React.ReactNode;
  onClick?: (e: React.SyntheticEvent<HTMLDivElement | HTMLAnchorElement>, arg?: number) => void;
  clickArg?: number;
  onContextMenu?: (e: React.UIEvent) => void;
  href?: string;
  download?: string;
  disabled?: boolean;
  destructive?: boolean;
  ariaLabel?: string;
  withWrap?: boolean;
};

const MenuItem: FC<MenuItemProps> = (props) => {
  const {
    icon,
    isCharIcon,
    customIcon,
    className,
    children,
    onClick,
    href,
    download,
    disabled,
    destructive,
    ariaLabel,
    withWrap,
    onContextMenu,
    clickArg,
  } = props;

  const lang = useLang();
  const { isTouchScreen } = useAppLayout();
  const handleClick = useLastCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (disabled || !onClick) {
      e.stopPropagation();
      e.preventDefault();

      return;
    }

    onClick(e, clickArg);
  });

  const handleKeyDown = useLastCallback((e: React.KeyboardEvent<HTMLDivElement>) => {
    if (e.keyCode !== 13 && e.keyCode !== 32) {
      return;
    }

    if (disabled || !onClick) {
      e.stopPropagation();
      e.preventDefault();

      return;
    }

    onClick(e, clickArg);
  });

  const fullClassName = buildClassName(
    'MenuItem',
    className,
    disabled && 'disabled',
    destructive && 'destructive',
    !isTouchScreen && 'compact',
    withWrap && 'wrap',
  );

  const content = (
    <>
      {!customIcon && icon && (
        <i
          className={isCharIcon ? 'icon icon-char' : `icon icon-${icon}`}
          data-char={isCharIcon ? icon : undefined}
        />
      )}
      {customIcon}
      {children}
    </>
  );

  if (href) {
    return (
      <a
        tabIndex={0}
        className={fullClassName}
        href={href}
        download={download}
        aria-label={ariaLabel}
        title={ariaLabel}
        target={href.startsWith(window.location.origin) || IS_TEST ? '_self' : '_blank'}
        rel="noopener noreferrer"
        dir={lang.isRtl ? 'rtl' : undefined}
        onClick={onClick}
      >
        {content}
      </a>
    );
  }

  return (
    <div
      role="menuitem"
      tabIndex={0}
      className={fullClassName}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      onContextMenu={onContextMenu}
      aria-label={ariaLabel}
      title={ariaLabel}
      dir={lang.isRtl ? 'rtl' : undefined}
    >
      {content}
    </div>
  );
};

export default MenuItem;
