// src/components/ui/svelte/RippleEffect.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  
  interface Ripple {
    id: number;
    x: number;
    y: number;
    size: number;
  }

  let ripples = $state<Ripple[]>([]);
  const ANIMATION_DURATION_MS = 700;
  let nextId = 0;

  function handleMouseDown(e: MouseEvent) {
    if (e.button !== 0) return;

    const container = e.currentTarget as HTMLDivElement;
    const position = container.getBoundingClientRect();
    const rippleSize = container.offsetWidth / 2;

    const newRipple = {
      id: nextId++,
      x: e.clientX - position.left - (rippleSize / 2),
      y: e.clientY - position.top - (rippleSize / 2),
      size: rippleSize,
    };

    ripples.push(newRipple);

    setTimeout(() => {
      ripples = ripples.filter(r => r.id !== newRipple.id);
    }, ANIMATION_DURATION_MS);
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="ripple-container" onmousedown={handleMouseDown}>
  {#each ripples as { id, x, y, size } (id)}
    <div
      class="ripple-wave"
      style:left="{x}px"
      style:top="{y}px"
      style:width="{size}px"
      style:height="{size}px"
    ></div>
  {/each}
</div>

<style lang="scss">
  @import "../RippleEffect.scss";
</style>

// src/components/ui/RippleEffect.tsx
import { memo, useMemo, useState } from '../../lib/teact/teact';

import { debounce } from '../../util/schedulers';

import useLastCallback from '../../hooks/useLastCallback';

import './RippleEffect.scss';

interface Ripple {
  x: number;
  y: number;
  size: number;
}

const ANIMATION_DURATION_MS = 700;

const RippleEffect = () => {
  const [ripples, setRipples] = useState<Ripple[]>([]);

  const cleanUpDebounced = useMemo(() => {
    return debounce(() => {
      setRipples([]);
    }, ANIMATION_DURATION_MS, false);
  }, []);

  const handleMouseDown = useLastCallback((e: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    if (e.button !== 0) {
      return;
    }

    const container = e.currentTarget;
    const position = container.getBoundingClientRect();
    const rippleSize = container.offsetWidth / 2;

    setRipples([
      ...ripples,
      {
        x: e.clientX - position.x - (rippleSize / 2),
        y: e.clientY - position.y - (rippleSize / 2),
        size: rippleSize,
      },
    ]);

    cleanUpDebounced();
  });

  return (
    <div className="ripple-container" onMouseDown={handleMouseDown}>
      {ripples.map(({ x, y, size }) => (
        <div
          className="ripple-wave"
          style={`left: ${x}px; top: ${y}px; width: ${size}px; height: ${size}px;`}
        />
      ))}
    </div>
  );
};

export default memo(RippleEffect);
